//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 1 images.
  struct image {
    /// Image `colorPicker`.
    static let colorPicker = Rswift.ImageResource(bundle: R.hostingBundle, name: "colorPicker")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "colorPicker", bundle: ..., traitCollection: ...)`
    static func colorPicker(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.colorPicker, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 16 localization keys.
    struct localizable {
      /// en translation: Background color
      ///
      /// Locales: en, ka
      static let backgroundColor = Rswift.StringResource(key: "backgroundColor", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Close
      ///
      /// Locales: en, ka
      static let alertOk = Rswift.StringResource(key: "alertOk", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Continue
      ///
      /// Locales: en, ka
      static let continueButton = Rswift.StringResource(key: "continueButton", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Foreground color
      ///
      /// Locales: en, ka
      static let foregroundColor = Rswift.StringResource(key: "foregroundColor", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Not Sure how to use widget?
      ///
      /// Locales: en, ka
      static let widgetGuide = Rswift.StringResource(key: "widgetGuide", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Personal Pin
      ///
      /// Locales: en, ka
      static let pinInputPlaceholder = Rswift.StringResource(key: "pinInputPlaceholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Phone
      ///
      /// Locales: en, ka
      static let phoneInputPlaceholder = Rswift.StringResource(key: "phoneInputPlaceholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: SMS Code
      ///
      /// Locales: en, ka
      static let otpCodeAlertTitle = Rswift.StringResource(key: "otpCodeAlertTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: SMS Code
      ///
      /// Locales: en, ka
      static let smsInputPlaceholder = Rswift.StringResource(key: "smsInputPlaceholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Something went wrong
      ///
      /// Locales: en, ka
      static let alertTitle = Rswift.StringResource(key: "alertTitle", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: The code is incorrect or has expired, Wait for me to send you a new one and enter it correctly
      ///
      /// Locales: en, ka
      static let otpCodeAlertMessage = Rswift.StringResource(key: "otpCodeAlertMessage", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: To restrict unauthorised user from accessing the app
      ///
      /// Locales: en, ka
      static let appBiometryAll = Rswift.StringResource(key: "AppBiometryAll", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: To restrict unauthorised user from accessing the app
      ///
      /// Locales: en, ka
      static let appBiometryFaceId = Rswift.StringResource(key: "AppBiometryFaceId", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: To restrict unauthorised user from accessing the app
      ///
      /// Locales: en, ka
      static let appBiometryTouchId = Rswift.StringResource(key: "AppBiometryTouchId", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: Year of birth
      ///
      /// Locales: en, ka
      static let yearInputPlaceholder = Rswift.StringResource(key: "yearInputPlaceholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)
      /// en translation: You have entered something incorrectly
      ///
      /// Locales: en, ka
      static let alertMessage = Rswift.StringResource(key: "alertMessage", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ka"], comment: nil)

      /// en translation: Background color
      ///
      /// Locales: en, ka
      static func backgroundColor(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("backgroundColor", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "backgroundColor"
        }

        return NSLocalizedString("backgroundColor", bundle: bundle, comment: "")
      }

      /// en translation: Close
      ///
      /// Locales: en, ka
      static func alertOk(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("alertOk", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "alertOk"
        }

        return NSLocalizedString("alertOk", bundle: bundle, comment: "")
      }

      /// en translation: Continue
      ///
      /// Locales: en, ka
      static func continueButton(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("continueButton", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "continueButton"
        }

        return NSLocalizedString("continueButton", bundle: bundle, comment: "")
      }

      /// en translation: Foreground color
      ///
      /// Locales: en, ka
      static func foregroundColor(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("foregroundColor", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "foregroundColor"
        }

        return NSLocalizedString("foregroundColor", bundle: bundle, comment: "")
      }

      /// en translation: Not Sure how to use widget?
      ///
      /// Locales: en, ka
      static func widgetGuide(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("widgetGuide", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "widgetGuide"
        }

        return NSLocalizedString("widgetGuide", bundle: bundle, comment: "")
      }

      /// en translation: Personal Pin
      ///
      /// Locales: en, ka
      static func pinInputPlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("pinInputPlaceholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "pinInputPlaceholder"
        }

        return NSLocalizedString("pinInputPlaceholder", bundle: bundle, comment: "")
      }

      /// en translation: Phone
      ///
      /// Locales: en, ka
      static func phoneInputPlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("phoneInputPlaceholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "phoneInputPlaceholder"
        }

        return NSLocalizedString("phoneInputPlaceholder", bundle: bundle, comment: "")
      }

      /// en translation: SMS Code
      ///
      /// Locales: en, ka
      static func otpCodeAlertTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("otpCodeAlertTitle", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "otpCodeAlertTitle"
        }

        return NSLocalizedString("otpCodeAlertTitle", bundle: bundle, comment: "")
      }

      /// en translation: SMS Code
      ///
      /// Locales: en, ka
      static func smsInputPlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("smsInputPlaceholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "smsInputPlaceholder"
        }

        return NSLocalizedString("smsInputPlaceholder", bundle: bundle, comment: "")
      }

      /// en translation: Something went wrong
      ///
      /// Locales: en, ka
      static func alertTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("alertTitle", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "alertTitle"
        }

        return NSLocalizedString("alertTitle", bundle: bundle, comment: "")
      }

      /// en translation: The code is incorrect or has expired, Wait for me to send you a new one and enter it correctly
      ///
      /// Locales: en, ka
      static func otpCodeAlertMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("otpCodeAlertMessage", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "otpCodeAlertMessage"
        }

        return NSLocalizedString("otpCodeAlertMessage", bundle: bundle, comment: "")
      }

      /// en translation: To restrict unauthorised user from accessing the app
      ///
      /// Locales: en, ka
      static func appBiometryAll(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("AppBiometryAll", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "AppBiometryAll"
        }

        return NSLocalizedString("AppBiometryAll", bundle: bundle, comment: "")
      }

      /// en translation: To restrict unauthorised user from accessing the app
      ///
      /// Locales: en, ka
      static func appBiometryFaceId(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("AppBiometryFaceId", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "AppBiometryFaceId"
        }

        return NSLocalizedString("AppBiometryFaceId", bundle: bundle, comment: "")
      }

      /// en translation: To restrict unauthorised user from accessing the app
      ///
      /// Locales: en, ka
      static func appBiometryTouchId(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("AppBiometryTouchId", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "AppBiometryTouchId"
        }

        return NSLocalizedString("AppBiometryTouchId", bundle: bundle, comment: "")
      }

      /// en translation: Year of birth
      ///
      /// Locales: en, ka
      static func yearInputPlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("yearInputPlaceholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "yearInputPlaceholder"
        }

        return NSLocalizedString("yearInputPlaceholder", bundle: bundle, comment: "")
      }

      /// en translation: You have entered something incorrectly
      ///
      /// Locales: en, ka
      static func alertMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("alertMessage", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "alertMessage"
        }

        return NSLocalizedString("alertMessage", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R {
  fileprivate init() {}
}
